require.config({
	baseUrl:"/",
	paths:{
		"header":"module/header",
		"footer":"module/footer",
		"jquery":"libs/jquery/jquery-1.11.3",
		"bootstrap":"libs/bootstrap/js/bootstrap",
		"tools":"libs/tools",
		"indexImg":"module/indexImg",
		"template":"libs/template-web",
		"cookie":"libs/jquery.cookie"
	},
	//垫片
	shim:{
		"bootstrap":{
			deps:["jquery"]
		}
	}
})
